TRUNCATE TABLE user;
INSERT INTO USER (first_name, last_name, user_name, email, password) VALUES  ('Parker','Lubowitz','Patton Down DeHatches','lanette.cronin.dvm@yahoo.com','DmFPPuM9');
INSERT INTO USER (first_name, last_name, user_name, email, password) VALUES  ('Gray','Buckridge','Misty Shore','granville.rempel.lld@hotmail.com','ztThfXcB');
INSERT INTO USER (first_name, last_name, user_name, email, password) VALUES  ('Armani','Bartoletti','Evan Lee Arps','clifford.grant@gmail.com','yyOyZxyf');
INSERT INTO USER (first_name, last_name, user_name, email, password) VALUES  ('Spencer','Hilpert','Annie Matter','ladonna.rutherford@hotmail.com','N34V2V7e');
INSERT INTO USER (first_name, last_name, user_name, email, password) VALUES  ('Quinn','Littel','Annette Curtain','rev.lanie.brakus@yahoo.com','Z0fjMj3a');
INSERT INTO USER (first_name, last_name, user_name, email, password) VALUES  ('Briar','McDermott','Anita Bath','ema.walsh@hotmail.com','QpwCyfoD');
INSERT INTO USER (first_name, last_name, user_name, email, password) VALUES  ('Jordan','Reilly','Missy Sippy','chiquita.kub@hotmail.com','xyaeqYbq');
INSERT INTO USER (first_name, last_name, user_name, email, password) VALUES  ('Drew','Fahey','Iona Ford','dick.mayert.esq@gmail.com','FdEaLUps');
INSERT INTO USER (first_name, last_name, user_name, email, password) VALUES  ('Quinn','Ernser','Max Little','myrtle.kulas.cpa@yahoo.com','5Gg1RjUH');
INSERT INTO USER (first_name, last_name, user_name, email, password) VALUES  ('Justice','Ratke','Brock Lee','msgr.oralee.marvin@hotmail.com','dvfUErtM');
INSERT INTO USER (first_name, last_name, user_name, email, password) VALUES  ('Alexis','Wehner','Jed I. Knight','fr.mayme.luettgen@hotmail.com','f2yBeOyf');